import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import NavigationBar from '@/components/NavigationBar';
import { RealtimeInvoiceDashboard } from '@/components/RealtimeInvoiceDashboard';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Activity, Zap, Shield } from 'lucide-react';
const RealtimeMonitor = () => {
    return (_jsxs("div", { className: "min-h-screen bg-background", children: [_jsx(NavigationBar, {}), _jsxs("div", { className: "container mx-auto px-4 py-8", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-4xl font-bold mb-4", children: "Real-Time Blockchain Monitor" }), _jsx("p", { className: "text-muted-foreground text-lg mb-6", children: "Live WebSocket integration with Hiro Stacks API for instant transaction tracking and invoice lifecycle monitoring" })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-4 mb-8", children: [_jsx(Card, { children: _jsxs(CardHeader, { children: [_jsx(Activity, { className: "w-8 h-8 mb-2 text-blue-600" }), _jsx(CardTitle, { children: "WebSocket Connection" }), _jsx(CardDescription, { children: "Real-time blockchain event streaming via Hiro API" })] }) }), _jsx(Card, { children: _jsxs(CardHeader, { children: [_jsx(Zap, { className: "w-8 h-8 mb-2 text-orange-600" }), _jsx(CardTitle, { children: "Instant Updates" }), _jsx(CardDescription, { children: "Sub-second latency for invoice status changes" })] }) }), _jsx(Card, { children: _jsxs(CardHeader, { children: [_jsx(Shield, { className: "w-8 h-8 mb-2 text-green-600" }), _jsx(CardTitle, { children: "Contract Monitoring" }), _jsx(CardDescription, { children: "Track escrow contract events and mempool transactions" })] }) })] }), _jsx(RealtimeInvoiceDashboard, {}), _jsxs(Card, { className: "mt-8 bg-gradient-to-r from-blue-50 to-purple-50", children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Technical Implementation" }) }), _jsx(CardContent, { children: _jsxs("div", { className: "grid md:grid-cols-2 gap-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-2", children: "\uD83D\uDCE1 WebSocket Features" }), _jsxs("ul", { className: "text-sm space-y-1 text-muted-foreground", children: [_jsx("li", { children: "\u2022 Address transaction subscriptions" }), _jsx("li", { children: "\u2022 Contract call monitoring" }), _jsx("li", { children: "\u2022 Mempool transaction tracking" }), _jsx("li", { children: "\u2022 Automatic reconnection handling" })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-2", children: "\uD83D\uDD0D Event Tracking" }), _jsxs("ul", { className: "text-sm space-y-1 text-muted-foreground", children: [_jsx("li", { children: "\u2022 Invoice creation (create-invoice)" }), _jsx("li", { children: "\u2022 Escrow funding (ack-deposit)" }), _jsx("li", { children: "\u2022 Payment release (release-funds)" }), _jsx("li", { children: "\u2022 Dispute creation (create-dispute)" })] })] })] }) })] })] })] }));
};
export default RealtimeMonitor;
